apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system/
  - efk-logging/overlays/dev
  - karpenter/overlays/dev
  - karpenter/nodepool/overlays/dev
  - sealed-secrets/overlays/dev
  - thanos/overlays/dev