apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - thanos-objstore-sealed-secret.yaml
  - query-deployment.yaml
  - query-service.yaml
  - storegateway-statefulset.yaml
  - storegateway-service.yaml
  - compactor-deployment.yaml
