apiVersion: v1
kind: Service
metadata:
  name: thanos-storegateway
  namespace: monitoring
  labels:
    app: thanos-storegateway
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: grpc
      port: 10901
      targetPort: grpc
  selector:
    app: thanos-storegateway
