---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: thanos-objstore-secret
  namespace: monitoring
spec:
  encryptedData:
    objstore.yml: AgCtDEPuOO3RXqLXTBhgiW1JwiWaMsIv4Vv5Rbabwbu7PaSYChcJ6D/dipNRm43jNPd9/FrJjoq79iP5+I+iHWMDcV5iEasdf27pN8oag3O64iLt5ckI5Q7FUQA5zvIHSj4Rtnad86nFkMKFa8t8oYFRWk2SCgl1ZK+WMQgR9+WKWs0ivoTTr5IMw2AUbR6DjGU+RjWB6FwyGHPd6ux917cx3wtbJ9vRK1nm4Bh/5/hovS9o0aTuD/+vx7kckwsZ2z75Ya2ONWTu8onB2NSVWys0HTxqMsuvDrFmGedyBmC42m+u81JCTjUKw1Z/svrKwiP9OC5bSZ8T7anuzB7JgQ5koqXQhEpoERTCEQ+BqJSFpNxrGVMXN2Tjd95Yeu7a/pFHRRKzi0X+LYqwZCf0SldkmfRkzy4VSVRSm6A8DwufXNeQeUEAsmRt77kkMNSYWX4WTQ9Y5stynt+owA4pZ0sFtC14wiZc5OrZ0tbWpyem4m3nSyYkK3fR2qmOBprtn2t5wL9Ro9f5qBLnsaXeffHkX//mKBJbgR6DMDfY1YkYdRSoANc++CnGXltc3Yut5RdNUaPurTdG4lmVTB8wBwhX+xOPIuL9kYE7aTt0Qa2YzArEcaO7Pjfc9WZ4plHzcUiNpj/VSMZPpgHSswPifUEKPeaXaWd6JuQuMjxLgyieh4IJDS2WCPzkiPE26oior4RkzZMCtUdfJzUNPuera9ORC/YrcwYNlq2Q1/mM/eBVIDUA2oWDqwJX2obmjiwTNR90I2QbSoMYFOFtprxo/0XmMz6jrDDTfh4VqaMsL91B0he1vNddv7WPYxoiB6Z9nr1hCP/e
  template:
    metadata:
      name: thanos-objstore-secret
      namespace: monitoring
