apiVersion: v1                                            # Core Kubernetes API
kind: ServiceAccount                                     # Identity for pods to access the Kubernetes API
metadata:
  name: "{{ .Release.Name }}-kube-state-metrics"            # Dedicated identity for kube-state-metrics pods
  namespace: {{ .Values.namespace }}                      # Namespace where kube-state-metrics runs


# SUMMARY:
# This ServiceAccount is the identity used by the kube-state-metrics pods.
# It gets permissions through a ClusterRole + ClusterRoleBinding so it can read cluster objects and expose them as Prometheus metrics.