apiVersion: v1                             # Core Kubernetes API group for basic objects
kind: ServiceAccount                      # Creates an identity for a Pod to use
metadata:
  name: "{{ .Release.Name }}-server"        # Helm release name + suffix (ex: prometheus-server)
  namespace: {{ .Values.namespace }}      # Namespace where Prometheus is installed (ex: monitoring)
  # Purpose:
  # - Prometheus pods run as this ServiceAccount
  # - RBAC permissions (ClusterRoleBinding) are granted to this identity
  # - Prometheus uses this identity token to talk to the K8s API securely