---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: efk-creds
  namespace: logging
spec:
  encryptedData:
    password: AgDYrGGDyW248z+zkqc4EPHiPg66vTh9clYSC0IUSipFi1ZtUKMLoWIxigqDWqI0d5glM+NrCw9Bj5J8ANAsd6WxsWNYagoAd/gzk77HoX9cwMdrR2894gP3ghMLbYaF0AYMOesQ55uAS9qxZDBjXRQwXuko8s3gNgCovcd0CQQJJd0gVeTLrSybPfo/0PAz+Mm1AVs+FegFl7uj2I662zTnMQ/bzhYT3CbiKyvWhu/19AGKHwqxUNXioPvx5Rg21ukEfgbZ4uMjb1ACCH1NRhvjlwYd8Xp/EUwYSA8dhhzgtdF3rckNYu3hd60Bg8byluqxmNBiUsrJa+GFHMjlpOy5RIP6iXBEQALq5X7esfU758FU3+rEDweAtq7Rhp+IJzfwJIBGWsmTz9BO0CsSjjQAiQSEU5USl6Do080gijQwQbWSBMVBFJPt3P36nwDlggGjm9dPd3Agq9yH/4HqBnCFikbEo330EYlm73DdpNjK61PHOhGQ6F/kOPYhAnvbqaR0Vx6TQLG5FY8Guk4xdLETMaIhVz61rRESun+2AU1k48gCyxWyxbHy9yK947YyxbMiJM19ckWGZ/TfWGBjTh7RveWWNAUQq7lR9OZVEVrn3HdrErn1/wGOaJ7jSSI3efxsZ9HIaYJp1J95AzdLrGBRAX9prwLD6Rhj7+DmaaOo2EeVAjyHaQAolJL9kqdzmUW4Lsi1e/33oitlOB6ukfAWAVwdAUzDd3Y=
    user: AgBnTYORR7Ny/6gKgBSEHcsdzSqSDiygUgX8GJC6aRfxw7goBJ4VyHHCbm0WF0MhpkYJmtmWdGenKYPxx5wg6ZW/HeabjYQULb9V7d2E2CPcPyuMuJCbvQIZdEGV9GU/TTNS5GxuOhIoI0rD9y6ZiC3L1eA9G3gQVVFerXQ6WEnejQeJdtA/T5Ve1aNM85l7RJ4eza7ofazCi0F1av6E1cX9LH41TsMWxgllW43hPDiFcchFHic/+X5tK2vx2A2eHXVuZc4GgtVtPyNEBOe9Pso+d5fbyI0Sd/945Fbb6yzANFRmxqHql7KSbit4GIsOz/3x4dW6jVBIrn08zAwApvWR3MaaUshzcPpkeBZNXN3rQEdjm3iD+RucPZZR7SQXwklIElw5I00Kk+sGI9OeXD27/mWdXtPWq1rO9/fqAn5FInYx1LzlekghRCmKpkwk2AmQIg8KTzBLNgopbDZy0jVve6WKyDyDg6TPINlHZomOqy9YN0TddVabGIHfu004XteLbsYiN7Uq+3t4OG8lBb1wp4Db7D+R7RLrS8xNnAJ2mvmyQ1fJzApmWrbr82r6Yg7xEXhsg6YqMctYIr634iYLOtLtJpx5dtwCt1FPlCIOHLALPRtkz/TyR3N1mcF7swhdwdmL3M1Wqb5R6VgN02wQUabZauMQNzaVVpLYGlnsVsAm4KpJxXSQusi+6gtdE3TEOpAVJ7Th
  template:
    metadata:
      name: efk-creds
      namespace: logging
