---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: efk-creds
  namespace: logging
spec:
  encryptedData:
    password: AgBj1bM4wIintPjA0Go6U8Cml2PZmgyADH/VLHm84wpKNTe1R/K88mhelNJHcKkM9YL6yWCuqvpPgS3mTMFyE0vJR76PKjLFDP/Yu95pD+LyiRsDgKCk/Xa1LNLbRm5pK4t4/PPcOaT6eudRf8m+395Lfwb+nvaEf6QF/MwHF5MNdgpu5SCB8Hj1ARaCiZ7pgQHCH0hHvpxQmwV0oMs4pB9jk66DJFblpxAA3V1yrGivFE3uqvno47vjbgkq8ggG9Qe0sPsGopJEQqxgRREyqHavQv+oZxR/ZurR5TYRCVG+ezYnqeWCc/OAZDHnz9SlLnxskam8HwXNYJu4W1nBCrWrVjSO8wzt9CAeP7C0gM3DSdSorFm2XOqUP1anr8Lmj5saC3KBLXsRwse0Ar0Hzu2989oen8hG7T4zDvozEr8NXLGdat4qeIMr/V5xqq1rwTxgTfv8nnEID+ECr3hsee3TvjjyMCrQ46pahULRa3ETPGyPe/+g5RlasMUdK65RgWaUD6E67LWbjjJJb2hw7vPZCF9BCxE3+6HplbW13kQzehVwdVE/5R1frNiuzD8fSynr1J9hNQvJkQgPmj++JP84NqWrK/eu3HGuXfHQ8AvNNhhhFB4sDZMJ32q73JR457cyop+0ruMrkjLw49YMifky7QFqXHGAoqIySRSXLDNQ8pi/egottB2+nDB92jbK2bHyegsglPoomGY=
    user: AgC5bBl/dHbAPVjrO8ziS8vonjDg6F6ejNHR7UIlg+y8es6VqgPqk5VJa/85hEZBRo/amWM24nCm5NVRPS4qcR/pKfLkrOJuJcFj/6HHE2ZXlPYXRsNMVHHqiKVUXhzNbe6H7zm+7y+OZ4kq0QIu0VIN1Zef5wzB3fsvpRrBWmo7ktYrWaL1pyA7Es1I5tKZr9mA782hqvjHbhR4tlT9zBoMr8bxAn/DUJW2MND6wdaao7JbyZt5J4Icz7W1Mg+Pugl7SWBNDkEuo9QUzX92V3PmMHCVaSBtaS4Yprs5zDqiJKM2EvxAY412pPvK0WxQfP7OuY4jR0M/k+eCzwwld1pIPOgINBed0ACsWFi6PWPHdWxCgq+kfHNqY4Jc7h0Yz6/UONmbdQV11yhTvY6Vo9e/2e1R/4QDvHIkIN4uTT3uliBHoQntNTS/n16n9pPKKgjRMKpBaaX3gUTV+t3TOChcUSYGCPg8j+grpnT1YQsvCh/euH/ZkrPpi7vq4BSI8vKiAFnmz2tGIDMB8aj/XylJHwNF5Y96GT+h2nQLHz10BPfT1iRN3azZaQBsE2RmnJjamv7kKkXC4o8rewQVCS/LEXBm1rYwsrC+oa7xWQvbX0Z1tS4zrL+VzzD065uhhTPOmX8QNR45EuFWk90yVS+j8wdsuV97oKGjSPHWfmVomdY1GxAMvbY71qeYzP05HVsYZnjEeQ==
  template:
    metadata:
      name: efk-creds
      namespace: logging
